print("student information")
name=input("Enter the student name:")
age=input("enter the age of the student:")
sclass=input("enter the class of the student:")
school=input("enter the school name of the student:")
print("The student name is :",name)
print("the age of the student is:",age)
print("the class of the student is:",sclass)
print("the school name of the student is:",school)
